export default class Language {
  static AR = 'ar'
  static BE = 'be'
  static DE = 'de'
  static EN = 'en'
  static EN_GB = 'en-GB'
  static EN_US = 'en-US'
  static ES = 'es'
  static ES_MX = 'es-MX'
  static FI = 'fi'
  static FR = 'fr'
  static IT = 'it'
  static JA = 'ja'
  static KK = 'kk'
  static KO = 'ko'
  static NL = 'nl'
  static PL = 'pl'
  static PT = 'pt'
  static PT_BR = 'pt-BR'
  static RU = 'ru'
  static SV = 'sv'
  static UK = 'uk'
  static ZH_CN = 'zh-CN'
  static ZH_TW = 'zh-TW'
}
